version: "3.2"
services:
  db:
    image: postgres:alpine
    volumes:
      - ./.data/pgsql:/var/lib/postgresql/data
      # - ./src/Server/init.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PWD
      POSTGRES_DB: $PG_DB
      PGUSER: $PG_USER
      PGPASSWORD: $PG_PWD
      PGDATABASE: $PG_DB
  server:
    build:
      context: .
      target: build
      args:
        USER: $SV_USER
        USER_ID: $SV_USER_ID
        GROUP_ID: $SV_GROUP_ID
    volumes:
      - ./.data:/home/$SV_USER/.data
      - ./src:/home/$SV_USER/src/
      - ./tests:/home/$SV_USER/tests/
    depends_on:
      - db
    # command: bash -c "cd tests/Server && dotnet run"
    command: bash
    stdin_open: true
    tty: true
