version: 2
jobs:
  build:
    machine:
        image: circleci/ubuntu-2004:202008-01

    steps:
        - checkout
        - run: ./setup-dev.sh
        - run: docker-compose up -d
        - run: docker exec bat_server_1 sh -c "./run-tests.sh"
