// <auto-generated />
namespace Migrations.Sqlite

open Repository
open System
open System.Collections.Generic
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Migrations.Operations
open Microsoft.EntityFrameworkCore.Migrations.Operations.Builders
open Microsoft.EntityFrameworkCore.Storage.ValueConversion


type private ExchangeTransactionsTable = {
    Id: OperationBuilder<AddColumnOperation>
    Date: OperationBuilder<AddColumnOperation>
    FromCurrency: OperationBuilder<AddColumnOperation>
    ToCurrency: OperationBuilder<AddColumnOperation>
    Price: OperationBuilder<AddColumnOperation>
    Quantity: OperationBuilder<AddColumnOperation>
    Provider: OperationBuilder<AddColumnOperation>
}

[<DbContext(typeof<SqliteContext>)>]
[<Migration("20201001215937_Initial")>]
type Initial() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "ExchangeTransactions"
            ,columns = (fun table -> 
            {
                Id = table.Column<int>(nullable = false)
                    .Annotation("Sqlite:Autoincrement", true)
                Date = table.Column<DateTime>(nullable = false)
                FromCurrency = table.Column<int>(nullable = false)
                ToCurrency = table.Column<int>(nullable = false)
                Price = table.Column<decimal>(nullable = false)
                Quantity = table.Column<int>(nullable = false)
                Provider = table.Column<string>(nullable = true)
            })
            ,constraints =
                (fun table -> 
                    table.PrimaryKey("PK_ExchangeTransactions", (fun x -> (x.Id) :> obj)) |> ignore
                ) 
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "ExchangeTransactions"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "3.1.8")
             |> ignore

        modelBuilder.Entity("Shared.ExchangeTransaction", (fun b ->

            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER") |> ignore
            b.Property<DateTime>("Date")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("FromCurrency")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<decimal>("Price")
                .IsRequired()
                .HasColumnType("TEXT") |> ignore
            b.Property<string>("Provider")
                .HasColumnType("TEXT") |> ignore
            b.Property<int>("Quantity")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore
            b.Property<int>("ToCurrency")
                .IsRequired()
                .HasColumnType("INTEGER") |> ignore

            b.HasKey("Id") |> ignore

            b.ToTable("ExchangeTransactions") |> ignore

        )) |> ignore

